---
title: "TMS Data Processing"
format: html
editor_options: 
  chunk_output_type: console
---

# Setup

```{r}
library(tidyverse)
library(grafify)
```

# JCR


```{r}
# Define function for reading processed TMS data
read_tms_processed <- function(filename, start = NA, end = NA) {
  readxl::read_excel(filename) |>
    janitor::clean_names() |>
    rename(vwc_temp_corr = vol_moisture) |>
    rename(vwc = volumetric_soil_moisture_without_temp_correction) |>
    rename(temp_C = d) |>
    select(datetime, vwc, vwc_temp_corr, temp_C) |>
    mutate(datetime = lubridate::ymd_hm(datetime)) |>
    mutate(datetime = with_tz(datetime, tzone = "America/Los_Angeles")) |>
    mutate(filename = filename)
}

filter_tms_window <- function(tms_data, precip_time) {
  start <- precip_time - lubridate::hours(24)
  end <- precip_time + lubridate::hours(54)
  tms_data |>
    filter(datetime >= start & datetime <= end)
}
```


```{r}
jr679 <- read_tms_processed(
  "data/TAC_TOMST/JCR_ROS/JR_probe679_processed.xlsx"
) |>
  filter_tms_window(precip_time = lubridate::ymd_hms("2025-04-03 13:15:00")) |>
  mutate(site = "JCR", condition = "ROS")


jr679 |>
  ggplot(
    aes(
      x = datetime,
      y = vwc
    )
  ) +
  geom_line() +
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  labs(
    x = "",
    y = "Volumetric Water Content (VWC)"
  ) +
  theme(panel.grid.minor = element_blank())
```


```{r}
js671 <- read_tms_processed(
  "data/TAC_TOMST/JCR_SKY/JS_probe405_processed.xlsx"
) |>
  filter_tms_window(precip_time = lubridate::ymd_hms("2025-04-03 13:15:00")) |>
  mutate(site = "JCR", condition = "SKY")

js671 |>
  ggplot(
    aes(
      x = datetime,
      y = vwc
    )
  ) +
  geom_line() +
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  labs(
    x = "",
    y = "Volumetric Water Content (VWC)"
  ) +
  theme(panel.grid.minor = element_blank())
```

# LOM


```{r}
lr424 <- read_tms_processed(
  "data/TAC_TOMST/LOM - ROS/LR_probe424_processed.xlsx"
) |>
  filter_tms_window(precip_time = lubridate::ymd_hms("2025-04-16 12:00:00")) |>
  mutate(site = "LOM", condition = "ROS")

lr424 |>
  ggplot(
    aes(
      x = datetime,
      y = vwc
    )
  ) +
  geom_line() +
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  labs(
    x = "",
    y = "Volumetric Water Content (VWC)"
  ) +
  theme(panel.grid.minor = element_blank())
```


```{r}
ls413 <- read_tms_processed(
  "data/TAC_TOMST/LOM - SKY/LS_probe672_processed.xlsx"
) |>
  filter_tms_window(precip_time = lubridate::ymd_hms("2025-04-16 12:00:00")) |>
  mutate(site = "LOM", condition = "SKY")

ls413 |>
  ggplot(
    aes(
      x = datetime,
      y = vwc
    )
  ) +
  geom_line() +
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  labs(
    x = "",
    y = "Volumetric Water Content (VWC)"
  ) +
  theme(panel.grid.minor = element_blank())
```

# combined tibble


```{r}
combined <- bind_rows(
  jr679,
  js671,
  lr424,
  ls413
)
```


```{r}
combined_plot <- combined |>
  mutate(
    site = case_when(
      site == "JCR" ~ "Jalama Canyon Ranch",
      site == "LOM" ~ "Loma Ridge"
    ),
    condition = case_when(
      condition == "ROS" ~ "Drought",
      condition == "SKY" ~ "Control"
    )
  ) |>
  ggplot(
    aes(
      x = datetime,
      y = vwc,
      color = condition
    )
  ) +
  geom_line(linewidth = 1) +
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~site, scales = "free_x", ncol = 1) +
  scale_color_manual(values = c('Drought' = '#fc9403', 'Control' = '#03b1fc')) +
  theme_minimal() +
  labs(
    x = "",
    y = "Volumetric Water Content (VWC)",
    color = ""
  ) +
  theme(
    legend.title = element_blank(),
    panel.grid.minor = element_blank(),
    legend.background = element_rect(fill = "white", color = "black")
  )
combined_plot

ggsave(
  filename = "fig_output/TMS_VWC_data.pdf",
  plot = combined_plot,
  width = 3.8,
  height = 4.2,
  units = "in"
)
```

# Analyze full season datasets


```{r}
# Define a function for filtering TMS data within our experimental season
filter_tms_season <- function(tms_data, start_datetime, end_datetime) {
  tms_data |>
    filter(datetime >= start_datetime & datetime <= end_datetime)
}


jcr_data_full <- read_tms_processed(
  filename = "data/TAC_TOMST/JCR_ROS/JR_probe417_processed.xlsx"
) |>
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/JCR_ROS/JR_probe439_processed.xlsx"
  )) |>
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/JCR_ROS/JR_probe679_processed.xlsx"
  )) |>
  # SKY data
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/JCR_SKY/JS_probe405_processed.xlsx"
  )) |>
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/JCR_SKY/JS_probe_671_processed.xlsx"
  )) |>
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/JCR_SKY/JS_probe433_processed.xlsx"
  )) |>
  filter_tms_season(
    start_datetime = "2024-10-25 00:00:00",
    end_datetime = "2025-04-01 00:00:00"
  ) |>
  # add depth info
  mutate(
    depth_cm = case_when(
      # JCR Data
      str_detect(filename, "probe439") ~ "30 cm",
      str_detect(filename, "probe417") ~ "20 cm",
      str_detect(filename, "probe679") ~ "10 cm",
      str_detect(filename, "probe433") ~ "30 cm",
      str_detect(filename, "probe405") ~ "20 cm",
      str_detect(filename, "probe_671") ~ "10 cm"
    ),
    condition = case_when(
      str_detect(filename, "ROS") ~ "Drought",
      str_detect(filename, "SKY") ~ "Control"
    ),
    site = "Pasture"
  )


lom_data_full <- read_tms_processed(
  filename = "data/TAC_TOMST/LOM - ROS/LR_probe401_processed.xlsx"
) |>
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/LOM - ROS/LR_probe424_processed.xlsx"
  )) |>
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/LOM - ROS/LR_probe667_processed.xlsx"
  )) |>
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/LOM - SKY/LS_probe413_processed.xlsx"
  )) |>
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/LOM - SKY/LS_probe434_processed.xlsx"
  )) |>
  bind_rows(read_tms_processed(
    filename = "data/TAC_TOMST/LOM - SKY/LS_probe672_processed.xlsx"
  )) |>
  filter_tms_season(
    start_datetime = "2025-03-04 00:00:00",
    end_datetime = "2025-04-15 06:00:00"
  ) |>
  mutate(
    depth_cm = case_when(
      # Loma Ridge Data:
      str_detect(filename, "probe434") ~ "30 cm",
      str_detect(filename, "probe413") ~ "20 cm",
      str_detect(filename, "probe672") ~ "10 cm",
      str_detect(filename, "probe424") ~ "30 cm",
      str_detect(filename, "probe401") ~ "20 cm",
      str_detect(filename, "probe667") ~ "10 cm",
    ),
    condition = case_when(
      str_detect(filename, "ROS") ~ "Drought",
      str_detect(filename, "SKY") ~ "Control"
    ),
    site = "Grassland"
  )
``` 

```{r}
p_jcr_data_full <- jcr_data_full |>
  filter(!str_detect(filename, "probe417")) |> # remove faulty data
  ggplot(
    aes(
      x = datetime,
      y = vwc,
      color = depth_cm
    )
  ) +
  geom_line() +
  facet_wrap(vars(condition), ncol = 1) +
  scale_y_continuous(labels = scales::percent) +
  coord_cartesian(ylim = c(0, 0.5)) +
  scale_color_grafify(palette = "r4") +
  labs(
    x = "",
    y = "VWC (%)",
    color = "Sensor Depth",
    title = "Jalama Canyon Ranch - Cattle Pasture"
  ) +
  theme_minimal()
p_jcr_data_full

p_lom_data_full <- lom_data_full |>
  ggplot(
    aes(
      x = datetime,
      y = vwc,
      color = depth_cm
    )
  ) +
  geom_line() +
  facet_grid(condition ~ depth_cm) +
  scale_y_continuous(labels = scales::percent) +
  coord_cartesian(ylim = c(0, 0.5)) +
  scale_color_grafify(palette = "r4") +
  labs(
    x = "",
    y = "VWC (%)",
    color = "Sensor Depth",
    title = "Loma Ridge - Grassland"
  ) +
  theme_minimal()
p_lom_data_full

p_full_combined <- cowplot::plot_grid(
  p_jcr_data_full,
  p_lom_data_full,
  ncol = 1,
  align = "v"
)
p_full_combined

cowplot::save_plot(
  filename = "fig_output/TMS_full_season_VWC.pdf",
  plot = p_full_combined,
  base_height = 8,
  base_width = 6
)
```

# temperature plot


```{r}
jcr_data_full |> glimpse()

jcr_average_temps <- jcr_data_full |>
  group_by(site, condition, depth_cm) |>
  summarise(
    mean_temp = mean(temp_C, na.rm = TRUE)
  )

p_jcr_temp <- jcr_data_full |>
  filter(site == "Pasture") |>
  ggplot(
    aes(
      x = datetime,
      y = temp_C,
    )
  ) +
  geom_line(alpha = 0.3, color = "gray") +
  geom_hline(data = jcr_average_temps, aes(yintercept = mean_temp)) +
  facet_grid(depth_cm ~ condition) +
  geom_smooth() +
  labs(
    y = "Temperature (C)",
    x = "",
    title = "Pasture - Jalama Canyon Ranch"
  ) +
  theme_minimal()
```


```{r}
lom_data_full |>
  glimpse()


lom_average_temps <- lom_data_full |>
  group_by(site, condition, depth_cm) |>
  summarise(
    mean_temp = mean(temp_C, na.rm = TRUE)
  )

p_loma_temp <- lom_data_full |>
  ggplot(
    aes(
      x = datetime,
      y = temp_C,
    )
  ) +
  geom_line(alpha = 0.3, color = "gray") +
  geom_hline(data = lom_average_temps, aes(yintercept = mean_temp)) +
  facet_grid(depth_cm ~ condition) +
  geom_smooth() +
  labs(
    y = "Temperature (C)",
    x = "",
    title = "Grassland - Loma Ridge"
  ) +
  theme_minimal()
```


```{r}
p_combined <- cowplot::plot_grid(plot = p_jcr_temp, p_loma_temp)
p_combined

cowplot::save_plot(
  plot = p_combined,
  filename = "fig_output/soil_temp_combined.pdf",
  base_height = 6,
  base_width = 8
)
```


```{r}
jcr_average_temps |> bind_rows(lom_average_temps)
```