---
title: "gRodon"
format: html
---

## Installation
 Per the [gRodon GitHub page](https://github.com/jlw-ecoevo/gRodon2), the easist way to install gRodon is through `devtools`:

```{r}
devtools::install_github("jlw-ecoevo/gRodon2")
```

## Run the minimal example


```{r}
library(gRodon)
library(Biostrings)

# load in example genome (streptococcuys pyogenes M1, downloaded from RefSeq)
# included with gRodon
path_to_genome <- system.file(
  'extdata',
  'GCF_000349925.2_ASM34992v2_cds_from_genomic.fna.gz',
  package = 'gRodon'
)

# read the DNA sequence
genes <- readDNAStringSet(path_to_genome)

# search pre-existing annotations for ribosomal proteins, which we will use as our set of target "highly expressed" genes
# use grepl for pattern matching (grep returns a character vector containing selected elements, grepl returns a logical vector (match or not for each element of x))
highly_expressed <- grepl("ribosomal protein", names(genes), ignore.case = TRUE)

# Run the gRodon growth prediction pipeline
example_results <- predictGrowth(genes, highly_expressed)
```

gRodon returns a list with the following elements:
```
# CUBHE: median codon usage bias of the highly expressed genes (MILC) calculated using the genbome-wide codon usage as the expected bias
$CUBHE
[1] 0.9148924

# GC: GC content
$GC
[1] 0.3917167

$GCdiv
[1] 0.1082833

# Mean codon usage bias of the highly expressed genes (MILC) calculated using the codon usage of highly expressed genes as the expected bias
$ConsistencyHE
[1] 0.5062119

$CUB
[1] 0.564834

# CPB: Genome-wide codon pair bias
$CPB
[1] -0.3886505

# Filtered sequences: number of gene sequences filtered out during calculation (due to length and/or presence of ambiguous bases)
$FilteredSequences
[1] 146

$nHE
[1] 45

$dCUB
[1] -0.6197544

# predicted doubling time in hours
$d
[1] 0.364274

# lower CI of D (2.5%) from linear model
$LowerCI
[1] 0.2976978

# Upper CI of d (97.5%) from linear model
$UpperCI
[1] 0.4483901
```
The output is a list and we can pull doubling time and CI with simple dollar sign notation:

```{r}
example_results_tibble <- dplyr::tibble(
  organism = "Streptococcus pyogenes M1",
  doubling_time = example_results$d,
  lower_CI = example_results$LowerCI,
  upper_CI = example_results$UpperCI
)
example_results_tibble
```