---
title: "Weather data"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# JCR weather thru 2024

```{r}
library(tidyverse)
```

```{r}
jcr_weather <- read_csv(
  "data/Weather Data/Jalama Canyon Ranch Weather Station Data_10022024.csv"
)

# check col types
sapply(jcr_weather, class)
```

```{r}
p_jcr_precip <- jcr_weather |>
  pivot_longer(
    cols = c(dayRain_c, monthRain_c, yearRain_c),
    names_to = "type",
    values_to = "rain_c"
  ) |>
  mutate(
    type = case_when(
      type == "dayRain_c" ~ "Daily Precipitation",
      type == "monthRain_c" ~ "Monthly Precipitation",
      type == "yearRain_c" ~ "Annual Precipitation"
    ),
    type = factor(
      type,
      levels = c(
        "Daily Precipitation",
        "Monthly Precipitation",
        "Annual Precipitation"
      )
    )
  ) |>

  ggplot(
    aes(
      x = utcdatetime,
      y = rain_c,
      color = type
    )
  ) +
  geom_line() +
  scale_color_brewer(palette = "Set1") +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%Y %b") +
  labs(
    x = "Date",
    y = "Precipitation (inches)",
    color = ""
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

p_jcr_precip

# cowplot::save_plot(
#   filename = "fig_output/jcr_precip.pdf",
#   plot = p_jcr_precip,
#   base_height = 5,
#   base_width = 8
# )
```

```{r}
jcr_weather |>
  pivot_longer(
    cols = c(dayRain_c, monthRain_c, yearRain_c),
    names_to = "type",
    values_to = "rain_c"
  ) |>
  mutate(
    type = case_when(
      type == "dayRain_c" ~ "Daily Precipitation",
      type == "monthRain_c" ~ "Monthly Precipitation",
      type == "yearRain_c" ~ "Annual Precipitation"
    ),
    type = factor(
      type,
      levels = c(
        "Daily Precipitation",
        "Monthly Precipitation",
        "Annual Precipitation"
      )
    )
  ) |>
  filter(type == "Daily Precipitation") |>
  ggplot(
    aes(
      x = utcdatetime,
      y = rain_c,
      color = type
    )
  ) +
  geom_line() +
  scale_color_brewer(palette = "Set1") +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%Y %b") +
  labs(
    x = "Date",
    y = "Precipitation (inches)",
    color = ""
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r}
jcr_weather |>
  ggplot(
    aes(
      x = utcdatetime,
      y = temp
    )
  ) +
  geom_line() +
  tidyquant::geom_ma(ma_fun = SMA, n = 365, linetype = "solid", color = "red") +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%Y %b") +
  labs(
    x = "",
    y = "Temperature (F)"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

# JCR weather thru 2025

```{r}
jcr_new <- read_csv(
  "data/Weather Data/Jalama Canyon Ranch Rainfall 08042024 to 08072025.csv"
) |>
  janitor::clean_names() |>
  rename(datetime = localizeddatetime_r_n) |>
  mutate(
    datetime = str_remove(datetime, "\\\\r\\\\n'$"),
    datetime = lubridate::ymd_hms(datetime),
    year = lubridate::year(datetime),
    month = lubridate::month(datetime),
    day = lubridate::day(datetime),
    date = lubridate::date(datetime),
    yearmonth = lubridate::floor_date(datetime, "month")
  ) |>
  select(datetime, date, yearmonth, month, day, everything()) |>
  filter(datetime < "2025-04-20 00:00:00", datetime > "2024-10-01 00:00:00") |>
  group_by(date) |>
  summarise(
    total_rain_per_day = max(day_rain_c, na.rm = TRUE)
  ) |>
  ungroup() |>
  mutate(accumulated_rain = cumsum(total_rain_per_day))


p_jcr_new <- jcr_new |>
  ggplot(
    aes(x = date, y = accumulated_rain)
  ) +
  geom_area(fill = "gray", alpha = 0.25) +
  geom_line() +
  geom_vline(
    xintercept = lubridate::ymd_hms("2025-04-02 00:00:00"),
    color = "blue",
    linetype = "dashed"
  ) +
  scale_y_continuous(
    breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8),
    sec.axis = sec_axis(
      transform = ~ . * 25.4,
      name = "Accumulated Precipitation (mm)"
    )
  ) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  coord_cartesian(expand = FALSE) +
  theme_bw() +
  labs(
    x = "",
    y = "Accumulated Precipitation (in)",
    title = "Jalama Canyon Ranch (Cattle Pasture)"
  ) +
  theme(
    panel.grid = element_blank(),
    aspect.ratio = 1,
    plot.title = element_text(hjust = 0.5)
  )

p_jcr_new

```  

# LOM weather
  
  ```{r}
lom_weather <- read_csv(
  "data/Weather Data/HICKS_CYN.csv",
  skip = 3
) |>
  janitor::clean_names() |>
  rename(
    datetime = date_and_time,
    precip = total
  ) |>
  mutate(datetime = lubridate::parse_date_time(datetime, "HMS mdy")) |>
  mutate(total_precip = cumsum(precip), total_precip_mm = total_precip * 25.4)

p_lom_weather <- lom_weather |>
  ggplot(
    aes(
      x = datetime,
      y = total_precip_mm / 25.4
    )
  ) +
  geom_area(fill = "gray", alpha = 0.25) +
  geom_line() +
  geom_vline(
    xintercept = lubridate::ymd_hms("2025-04-16 00:00:00"),
    color = "blue",
    linetype = "dashed"
  ) +
  scale_y_continuous(
    breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8),
    sec.axis = sec_axis(
      transform = ~ . * 25.4,
      name = "Accumulated Precipitation (mm)"
    )
  ) +
  coord_cartesian(expand = FALSE) +
  theme_bw() +
  labs(
    x = "",
    y = "Accumulated Precipitation (in)",
    title = "Loma Ridge (Grassland)"
  ) +
  theme(
    panel.grid = element_blank(),
    aspect.ratio = 1,
    plot.title = element_text(hjust = 0.5)
  )

p_lom_weather

```

# plot together

```{r}
p_combined <- cowplot::plot_grid(
  p_jcr_new,
  p_lom_weather,
  labels = c("A", "B"),
  ncol = 1
)

cowplot::save_plot(
  filename = "fig_output/combined_weather_data_plots.pdf",
  base_height = 8,
  base_width = 4,
  plot = p_combined
)
```